apiVersion: v1
kind: Pod
metadata:
  name: dvwa
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: vulnerables/web-dvwa
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
